projecttacoma/cqm-parsers

.github/PULL_REQUEST_TEMPLATE.md
This pull request adds a PR template to `js-ecqm-engine`, so the template you see below automagically gets added to every PR.
**Submitter:** Michael O'Keefe
Name:
Name:
=> Add Pull Request Template, copied from Cypress

Gemfile.lock, cqm-parsers.gemspec
cqm-parsers probably isn't ready for a 1.0 release yet, since there are additional parsers that need to get added. We'll plan on a 1.0 release once Bonnie starts using it.
**Submitter:**
Name:
=> Bump gem version down to 0.1.0, since it's never been published

Gemfile.lock, cqm-parsers.gemspec
In order to include them in the gem, add `.json`, `.mustache` and `.rake` files to the `.rb` files already included in `s.files`.
**Submitter:**
Name: @rbclark
=> Glob json/mustache/rake files as well

Gemfile, Gemfile.lock, cqm-parsers.gemspec, lib/qrda-export/catI-r5/_header.mustache, lib/qrda-export/catI-r5/qrda1_r5.mustache, lib/qrda-export/catI-r5/qrda1_r5.rb, lib/qrda-export/catI-r5/qrda_header/_author.mustache, lib/qrda-export/catI-r5/qrda_header/_custodian.mustache, lib/qrda-export/catI-r5/qrda_header/_documentation_of_service_event.mustache, lib/qrda-export/catI-r5/qrda_header/_legal_authenticator.mustache, lib/qrda-export/catI-r5/qrda_header/_record_target.mustache, lib/qrda-export/catI-r5/qrda_templates/device_ordered.mustache, lib/qrda-export/catI-r5/qrda_templates/encounter_ordered.mustache, lib/qrda-export/catI-r5/qrda_templates/medication_discharge.mustache, lib/qrda-export/catI-r5/qrda_templates/medication_dispensed.mustache, lib/qrda-export/helper/cat_1_view_helper.rb, lib/qrda-export/helper/date_helper.rb, lib/qrda-import/base-importers/demographics_importer.rb, lib/qrda-import/base-importers/section_importer.rb, lib/qrda-import/patient_importer.rb, lib/util/hqmf_template_helper.rb
Add helper method for current time
Updates to QRDA header templateid extensions (found in HDS QRDA5 export by bonnie)
Import race, ethnicity, payer.
only export CCN when available
A Reason can be nested in a wrapped template (on import and export)
When provider information is available, use in export.  otherwise boilerplate
Update to use the QDM::ID
Race and ethnicGroupCode display name were exporting a fixed value
On export, look up all appropriate HQMF ids for a definition/status pair, not fixed values (they can change over time)
**Submitter:**
Name:
=> Cat 1 patch

Gemfile, Gemfile.lock, cqm-parsers.gemspec
Updating gemspec with mustache dependency.
**Submitter:**
Name: @daco101 
Name:@mayerm94
=> Including mustache dependency

Gemfile, Gemfile.lock, README.md, test/simplecov_init.rb
Set up codecov for code coverage.
To see this branch's coverage, go to https://codecov.io/gh/projecttacoma/cqm-parsers/branch/codecov
**Submitter:**
Name:
Name:
=> Set up codecov code coverage tool

lib/qrda-export/catI-r5/qrda_header/_record_target.mustache
There were 2 IDs in the "recordTarget" section of QRDA template, remove the one that was set to "Bonnie"
**Submitter:**
Name:
Name: @okeefm
=> Remove bonnie id

lib/qrda-export/catI-r5/qrda_templates/assessment_performed.mustache, lib/qrda-import/data-element-importers/assessment_performed_importer.rb
=> updated assessment performed template

.rubocop_todo.yml, lib/measure-loader/cql_loader.rb, lib/measure-loader/elm_parser.rb, lib/measure-loader/value_set_helpers.rb, lib/measure-loader/vsac_value_set_loader.rb, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2.xml, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2_Annotations.json, test/fixtures/measureloading/elm_xmls/OpioidMedicationLogic.xml, test/fixtures/measureloading/elm_xmls/OpioidMedicationLogic_Annotations.json, test/unit/measure-loader/cql_loader_test.rb, test/unit/measure-loader/elm_parser_test.rb, test/unit/measure-loader/value_set_loader_test.rb
Changes:
- only unique valuesets are fetched and added to the measure model
- drc valuesets are shared amongst composite and components
- measure id is removed from version for "Draft" valuesets (not needed with new model)
This PR also improves the Elm Parser to handle large elm files (n^2 to n time complexity for the code that finds the node type), and refactors some of elm parser for clarity and simplicity. I've run some "regressions" with the new vs old ElmParser, the only difference I see is that since I now rely on nokogiri to provide the unescaped strings from the xml (instead of doing manual escaping), "&#xd" / "&#13" are converted to "\r" (which I think is good, since it looks like we needed to replace this with "" in the fronent js code anyways).
Pull requests into cqm-parsers …
=> Improve valueset loading and Elm Parsing

Gemfile.lock, lib/qrda-import/base-importers/demographics_importer.rb
Originally the demographics code systems were being hard coded.  look them up
**Submitter:**
Name: @mayerm94 
Name:
=> Race was not being imported correctly (PR against v0.2.2) 

lib/qrda-export/catI-r5/qrda_templates/template_partials/_results.mustache, lib/qrda-import/base-importers/section_importer.rb, lib/qrda-import/data-element-importers/communication_from_patient_to_provider_importer.rb, lib/qrda-import/data-element-importers/communication_from_provider_to_patient_importer.rb, lib/qrda-import/data-element-importers/communication_from_provider_to_provider_importer.rb, lib/qrda-import/data-element-importers/diagnosis_importer.rb, lib/qrda-import/data-element-importers/diagnostic_study_performed_importer.rb, lib/qrda-import/data-element-importers/laboratory_test_performed_importer.rb, lib/qrda-import/data-element-importers/substance_administered_importer.rb
=> Result Template Id Update and Bugs found during checklist roundtrip (PR against v0.2.2)

lib/qrda-export/catI-r5/qrda_templates/template_partials/_reason.mustache
=> The reason template extension was updated to 2017-08-01 from 2014-12-01 (PR against v0.2.2)

lib/qrda-export/catI-r5/qrda_templates/diagnostic_study_performed.mustache
=> A Diagnostic Study Performed can have a reason.  export it. (PR against v0.2.2)

lib/hqmf-parser/cql/document_helpers/doc_population_helper.rb, lib/measure-loader/hqmf_measure_loader.rb, test/unit/measure-loader/cql_loader_test.rb
This is a work in progress for populating the hqmf_identifiers for the populations in a population set.  suggest someone more familar with the code base review/modify accordingly.
relates to https://github.com/projecttacoma/cqm-models/pull/85
**Submitter:**
Name: @hossenlopp
=> Add the hqmf identifier to a statement reference

Gemfile.lock, cqm-parsers.gemspec
=> update gemspec to 0.2.3

lib/measure-loader/source_data_criteria_loader.rb, test/unit/measure-loader/cql_loader_test.rb
**Submitter:**
Name: @hossenlopp
=> codeListId and hqmfOid are both needed for sdc uniqueness

lib/measure-loader/mat_measure_files.rb
Simply adds `.path` on to the parameter passed into the the zip loader. This was done by bonnie_bundler. It normalizes out the slight differences of the test, multipart and normal uploaded files by just asking them for the `path` of the file.
**Submitter:**
Name: @hackrm 
Name:
=> Fix issue with loading uploaded files from API

cqm-parsers.gemspec
=> update gemspec version number to 2.0.1

lib/util/vsac_api.rb
Fix: BONNIE-587 Error loading VSAC value sets(ONC jira id)
**Submitter:**
Name:
Name:
=> BONNIE-587 Error loading VSAC value sets(ONC jira id)

Gemfile.lock, cqm-parsers.gemspec
Updated cqm-parsers version in `bonnie_version`
**Submitter:**
Name:
Name:
=> Updated version of bonnie_version cqm-parser branch

lib/measure-loader/mat_measure_files.rb, lib/util/bundle_utils.rb
https://jira.cms.gov/browse/MAT-1175
- Remove exception from `create_from_zip_file`
- Add more specific exception to `unzip_measure_zip_into_hash`
- Fix and update exceptions in `get_measure_bundle`
- [Pull request in `bonnie`](https://github.com/projecttacoma/bonnie/pull/1471) 
---
**Submitter:**
Name:
Name:
=> Ensure Users Can Only Upload FHIR Measures Bundles

lib/measure-loader/bundle_loader.rb, test/unit/measure-loader/bundle_loader_test.rb
Requires https://github.com/MeasureAuthoringTool/fhir-mongoid-models/pull/21
**Submitter:**
Name:
Name:
=> Mat1356 measure bundle used resources

lib/measure-loader/bundle_loader.rb, test/unit/measure-loader/bundle_loader_test.rb
=> Mat 1617 handle null cms

Gemfile.lock, lib/measure-loader/bundle_loader.rb, lib/measure-loader/value_set_helpers.rb, lib/measure-loader/vsac_value_set_loader.rb, test/unit/measure-loader/bundle_loader_test.rb, test/unit/measure-loader/value_set_loader_test.rb
MAT-1536 Display Measure Details on Measure Dashboard
**Submitter:**
Name:
Name:
=> MAT-1536 display CQL & Valueset for selected measure

lib/measure-loader/bundle_loader.rb
Raise exception when identifier element is missing during guid check.
**Submitter:**
Name:
Name:
=> [MAT-1623] Raise exception when identifier property is missing.

lib/measure-loader/bundle_loader.rb
Follow Measure resource's Library ref when a partial or full URL.
Depending on which iteration of the MAT is used to package a measure, the Measure resource will either use a partial or full URL to identify the Library containing the measure logic. For UAT round 1, it is possible that both iterations of the MAT will be available to users.
Current production MAT packages Measure Resource's with partial URL Library references.
```
"library": [
"Library/8a788f25739040ca01739045420b0012"
]
```
Future production MAT will use full URLs:
```
"library": [
"http://ecqi.healthit.gov/ecqms/Library/CreateFhirProportionMeasure1597691499140"
]
```
**Submitter:**
Name:
Name:
=> Follow Measure Resource's Library reference when partial or full URL

lib/measure-loader/bundle_loader.rb, test/unit/measure-loader/bundle_loader_test.rb
Updating population set, observation, and stratification parsing to use the extracted measure_lib_name instead of expecting the measure name to match the measure library name. This is another edit to enable BoF to support the current and updated MAT FHIR packaged.
**Submitter:**
Name:
Name:
=> [MAT-1641] Updating pop set parsing to use extracted lib name instead of measure name

lib/measure-loader/bundle_loader.rb, test/unit/measure-loader/bundle_loader_test.rb
Overriding the default PATIENT calculation type to EPISODE_OF_CARE when the passed in episode_of_care option is set to true.
When `CQM::Measure.calculation_method` is set to `EPISODE_OF_CARE`, the uploaded measure's details page will display relavent text (box highlighting mine): 
**Submitter:**
Name:
Name:
=> [MAT-1685] Checking episode of care argument 

Gemfile, Gemfile.lock, lib/measure-loader/bundle_loader.rb
MAT-1711 Stop Storing Binary Files in Mongo
- updated parsing
**Submitter:**
Name:
Name:
=> MAT-1711 Stop Storing Binary Files in Mongo

lib/measure-loader/vsac_value_set_loader.rb
Missed updating the VS Loader utility (mostly for  currently skipped tests) to use the vsac api key.
**Submitter:**
Name:
Name:
=> [MAT-1759] VSAC Value Set Loader using API Key

lib/measure-loader/bundle_loader.rb
- Saving the user specified option for calculating SDEs.
- Updating pop set names when user provides custom names in api call.
**Submitter:**
Name:
Name:
=> Saving user options: Calculate SDEs & Custom population set names

lib/measure-loader/bundle_loader.rb, lib/util/bundle_utils.rb, test/unit/measure-loader/bundle_loader_test.rb
MAT-2263 measurement period is not initialized correctly in bonnie
**Submitter:**
Name:
Name:
=> MAT-2263 measurement period is not initialized correctly in bonnie

Gemfile.lock
MAT-2185  Add parsing support for Data Requirements with a Direct Reference Code
- model integration
**Submitter:**
Name:
Name:
=> MAT-2185 datarequirement parsing when codeFilter is code

lib/util/bundle_utils.rb
Adding time component when parsing measurement period from effective period.
- Bonnie saves patient data with seconds precision.
- Start date will have zeroed out time.
- End date will have 23:59:59.
**Submitter:**
Name:
Name:
=> [MAT-2264] Add time component to Measurement Period

lib/measure-loader/source_data_criteria_loader.rb
When QDM datatype template has includeSubTemplate, the single_code_concepts hash will not have a related key and return nil, causing an error when attempting to access the sub-hash.
([BONNIEMAT-740](https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-740) Cannot upload measure package to Bonnie)
**Submitter:**
Name:
Name:
=> Safe nav before sub-hash access when extracting fields from single code data criteria

lib/measure-loader/source_data_criteria_loader.rb
Replacing the safe nav with dig since Bonnie didn't like the safe nav syntax and dig is better designed for nested hashes.
**Submitter:**
Name:
Name:
=> [MAT-2492] Replace Safe Nav with Hash.dig

lib/util/bundle_utils.rb, test/unit/measure-loader/value_set_loader_test.rb
=> MAT-2680 JSON file name has changed in measure bundle

Gemfile.lock, lib/measure-loader/bundle_loader.rb
=> MAT-2712 Parse FHIR SDEs

lib/measure-loader/value_set_helpers.rb
MAT-2122 Dosage widget codesystem
**Submitter:**
Name:
Name:
=> MAT-2122 Dosage widget binding

lib/measure-loader/code_systems.json, lib/measure-loader/value_set_helpers.rb, test/unit/measure-loader/value_set_helpers_test.rb
=> MAT-2745 Update Codes/Codesystems to Pull from JSON FIle

Gemfile, Gemfile.lock, test/unit/measure-loader/value_set_helpers_test.rb, test/vcr_setup.rb
MAT-2555 update parsers to use mongoid models v0.0.4
**Submitter:**
Name:
Name:
=> MAT-2555 update parsers to use mongoid models v0.0.4

lib/measure-loader/mat_measure_files.rb
MAT-2804 Update Bonnie to support UTF8 - FHIR
**Submitter:**
Name:
Name:
=> MAT-2804 Update Bonnie to support UTF8 - FHIR

lib/measure-loader/value_set_helpers.rb
=> MAT-2867 add uuid for drc url

lib/util/bundle_utils.rb
Since Bonnie cannot create patient dateTime data with seconds, always set the measurement period seconds (milli) values to zero to ensure compatible comparisons.
**Submitter:**
Name:
Name:
=> MAT-3265 Set Measurement Period seconds values to zero

Gemfile.lock, cqm-parsers.gemspec
Bump Nokogiri to 1.12.5 to resolve security vuln. See (Improper Restriction of XML External Entity Reference (XXE) in Nokogiri on JRuby)[https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2rr5-8q37-2w7h] for more info.
This bump may not be needed since the vulnerability is currently reported to only affect JRuby.
**Submitter:**
Name:
Name:
=> Bump Nokogiri to Resolve CVE-2021-41098

cqm-parsers.gemspec
=> bump nokogiri in case of security vulnerability

Gemfile.lock, cqm-parsers.gemspec
Bump Nokogiri to 1.12.5 to resolve security vuln. See [Improper Restriction of XML External Entity Reference (XXE) in Nokogiri on JRuby](https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2rr5-8q37-2w7h) for more info.
This bump may not be needed since the vulnerability is currently reported to only affect JRuby.
**Submitter:**
Name:
Name:
=> Bump Nokogiri to Resolve CVE-2021-41098 (bonnie-on-fhir)

lib/measure-loader/elm_parser.rb, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2.xml, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2_Annotations.json, test/unit/measure-loader/elm_parser_test.rb
=> MAT-3708 Update CQM-Parser to Account for Comments in the ELM

lib/measure-loader/elm_parser.rb, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2.xml, test/fixtures/measureloading/elm_xmls/AntithromboticTherapyByEndofHospitalDay2_Annotations.json, test/unit/measure-loader/elm_parser_test.rb
* MAT-3708 Update CQM-Parser to Account for Comments in the ELM
* MAT-3708 display commented functions and defs
**Submitter:**
Name:
Name:
=> MAT-3708 Update CQM-Parser to Account for Comments in the ELM (#163)

cqm-parsers.gemspec
=> update nokogiri dependence to < 1.14

lib/measure-loader/vsac_value_set_loader.rb, lib/util/vsac_api.rb, test/fixtures/vcr_cassettes/measure__test_can_use_cache.yml, test/fixtures/vcr_cassettes/vsac_vs_include_draft_with_profile.yml, test/fixtures/vcr_cassettes/vsac_vs_no_options.yml, test/fixtures/vcr_cassettes/vsac_vs_not_found.yml, test/fixtures/vcr_cassettes/vsac_vs_release.yml, test/fixtures/vcr_cassettes/vsac_vs_version.yml, test/test_helper.rb, test/unit/measure-loader/bundle_loader_composite_test.rb, test/unit/measure-loader/bundle_loader_test.rb, test/unit/measure-loader/value_set_loader_test.rb, test/unit/vsac/vsac_api_auth_test.rb
VSAC is dropping support for its TGT/ST based authn flow. Instead, VSAC SVS API will support Basic Authentication in requests with the password set to the requester's UMLS API KEY.
- Replace TGT/ST authn flow with Basic Authn containing the umls api key.
- Update test to reflect default MP end dateTime having 00 seconds
**Submitter:**
Name:
Name:
=> [MAT-6046] Update VSAC Connection to use UMLS API KEY in Requests - Bonnie FHIR

lib/measure-loader/hqmf_measure_loader.rb, lib/measure-loader/mat_measure_files.rb
=> Support importing MADiE and MAT measure bundles

cqm-parsers.gemspec
=> increment version to 4.1.1.1
